### ISSUE TITLE
Getting segment effort streams does not appear to work

### ISSUE THREAD

**Issue by mkiang** [fawda123/rStrava#104]
The `get_streams()` function works as expected when retrieving activity streams; however, it does not appear to work when retrieving segment effort streams. 

E.g., running `get_streams(stoken, id = 12576013745, request = "activities")` will return a long stream as expected. However, running this for segment efforts returns a 404:

```
> get_streams(stoken, id = 3265366675164236880, request = "segment_efforts")
Error in get_streams(stoken, id = 3265366675164236800, request = "segment_efforts") : 
  Not Found (HTTP 404).
```

even though I know [this is a valid segment effort](https://www.strava.com/segment_efforts/3265366675164236880).

**Comment by fawda123** [comment]
@mkiang good catch, this is a floating point precision issue.  R loses precision on the `id` value for the segment since the number is too long.  Note the final digits in the error compared to function call. It should work if you pass the `id` argument as a character vector instead.  

This is not an issue I anticipated, so I've now required all the functions that use an `id` argument to accept only character strings.  This will be in the next release.
