### ISSUE TITLE
units

### ISSUE THREAD

**Issue by cassiel74** [fawda123/rStrava#18]
Units parameter is not taken into account

`get_elev_prof(my_acts, acts = c(6), key = mykey, units = "metric")`
and 
`get_heat_map(my_acts, acts = 6, alpha = 1, add_elev = T, f = 1, key = mykey, size = 2, col = 'Spectral', maptype = 'satellite', units="metric")`

do always produce a plot with imperial units.

**Comment by fawda123** [comment]
@cassiel74 I can't reproduce the error on my end, have you tried reinstalling from the latest commit?

**Comment by cassiel74** [comment]
Well, to be honest me too... I can't reproduce it.

BTW I downloaded my activities then tried to get_elev_prof and get_heat_map using units="metric" after noticed the feet and miles on the graph (without compile activities first) but nothing changed...

I reinstalled from latest commit after my other issue was closed... don't know if it matters

**Comment by fawda123** [comment]
Okay, I think I figured out your problem.  If you use a compiled activities list as input to either `get_heat_map` or `get_elev_prof`, the units argument has no effect.  This is because the units argument is used in `compile_activities` and it is not recycled if a compiled list is used to call the plot functions.  You need to recompile the input list with different units if you want to change the units in the plot.  

I made this a bit more clear in the documentation and also changed the functions to return a warning if there's a mismatch in units.  8bb5eee8be2cb7ff7c4b1c84cca60e36ad0ebc0e

Does that make sense?

**Comment by cassiel74** [comment]
Yep, you're right! 
I looked at `.Rhistory` and there's a `mylast <- compile_activities(my_acts[1])` at one point.
I was playing around with the functions at a first glance then I decided to sort everything out and "clean the house".

Apologize for the noise

**Comment by fawda123** [comment]
No problem, let me know if you find any more issues.
